# Based on: 
# https://project-renard.github.io/doc/development/meeting-log/posts/2016/05/03/windows-build-with-msys2/

image: Visual Studio 2019

environment:
  global:
    PROJECTNAME: shardoverse

  matrix:
    # MinGW:
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: stable

    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: nightly

    # MSVC:
    #- TARGET: i686-pc-windows-msvc
    #- TARGET: x86_64-pc-windows-msvc

install:
  - 'echo Start install & time /t'
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\x86_64-pc-windows-gnu_10_install.bat'
  - 'echo End install at: & time /t'

build_script:
  - 'echo Start build_script & time /t'
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\x86_64-pc-windows-gnu_20_build.bat'
  - 'echo End of build_script at: & time /t'

test_script:
  - 'echo Start test_script & time /t'
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\x86_64-pc-windows-gnu_30_test.bat'
  - 'echo End of test_script at: & time /t'
  
cache:
  - C:\Users\appveyor\.cargo\registry
  - target

# branches:
#   only:
#     # Release tags
#     - /^v\d+\.\d+\.\d+.*$/
#     - master

# notifications:
#   - provider: Email
#     on_build_success: false
# 
# # Building is done in the test phase, so we disable Appveyor's build phase:
# build: false
