# Based on the rust_belt v1.2.0,  https://github.com/johnthagen/rust-belt/blob/master/appveyor.yml 
# with additions from the "trust" template v0.1.2, https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
    PROJECT_NAME: shardoverse

  matrix:
      - TARGET: x86_64-pc-windows-msvc
        CHANNEL: stable

# Based on https://github.com/japaric/rust-everywhere/blob/master/appveyor.yml
install:
  # Print Powershell version.
  - ps: $PSVersionTable.PSVersion
  - ps: pwd
  - cinst wget
  - cinst 7zip.portable

  # Install Rust and Cargo
  - curl --fail --silent --show-error --location --output rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

  # Add GCC to PATH
  - set PATH=%PATH%;C:\msys64\mingw64\bin

  # Install SDL2_gfx (todo: fix extraction).
  #- curl --fail --silent --show-error --location --output sdl2_gfx.tar.gz https://sourceforge.net/projects/sdl2gfx/files/SDL2_gfx-1.0.4.tar.gz
  - wget --content-disposition -O sdl2_gfx.tar.gz -c https://sourceforge.net/projects/sdl2gfx/files/SDL2_gfx-1.0.4.tar.gz 
  - set DIRCMD=/O
  - dir
  - 7z.exe x sdl2_gfx.tar.gz 
  - del sdl2_gfx.tar.gz
  - dir
  - 7z.exe x sdl2_gfx.tar 
  - del sdl2_gfx-1.0.4.tar
  - dir
  - cd SDL2_gfx-* 
  - dir
  - ./autogen.sh 
  - ./configure 
  - make 
  - make install
  - cd ..
  #- set LIB=%LIB%;C:\projects\shardoverse\sdl2_gfx\SDL2_gfx-1.0.4\lib\x64
  - ps: Get-ChildItem -Recurse -Depth 4

  # Install SDL2.
  - curl --fail --silent --show-error --location --output sdl2.zip https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip
  - ps: Expand-Archive sdl2.zip -DestinationPath sdl2
  - set LIB=%LIB%;C:\projects\shardoverse\sdl2\SDL2-2.0.10\lib\x64

  # Install SDL2_ttf.
  - curl --fail --silent --show-error --location --output sdl2_ttf.zip https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip
  - ps: Expand-Archive sdl2_ttf.zip -DestinationPath sdl2_ttf
  - set LIB=%LIB%;C:\projects\shardoverse\sdl2_ttf\SDL2_ttf-2.0.15\lib\x64
  - ps: Get-ChildItem -Recurse -Depth 4

  # Install SDL2_Image.
  - curl --fail --silent --show-error --location --output sdl2_image.zip https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip
  - ps: Expand-Archive sdl2_image.zip -DestinationPath sdl2_image
  - set LIB=%LIB%;C:\projects\shardoverse\sdl2_image\SDL2_image-2.0.5\lib\x64
  - ps: Get-ChildItem -Recurse -Depth 4

  # Install SDL2_Mixer.
  - curl --fail --silent --show-error --location --output sdl2_mixer.zip https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip
  - ps: Expand-Archive sdl2_mixer.zip -DestinationPath sdl2_mixer
  - set LIB=%LIB%;C:\projects\shardoverse\sdl2_mixer\SDL2_mixer-2.0.4\lib\x64
  - ps: Get-ChildItem -Recurse -Depth 4

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo build --verbose
