# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: bionic
language: rust
sudo: required

git:
  depth: 3

env:
  global:
    - CRATE_NAME=shardoverse

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
    #- env: TARGET=x86_64-unknown-linux-musl

    # OSX
    #- env: TARGET=x86_64-apple-darwin
    #  os: osx

    # *BSD
    #- env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    #- env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

    # Windows
    #- env: TARGET=x86_64-pc-windows-gnu

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    #- env: TARGET=x86_64-apple-darwin
    #  os: osx
    #  rust: nightly

before_install:
  - echo Stage before_install
  - set -e
  - rustup self update

install:
  - echo Stage install
  - echo TargetDollar=$TARGET
  - echo TargetPercent=%TARGET%
  - if [%TARGET%]==[x86_64-unknown-linux-gnu] (
      bash ci/travisci/x86_64-unknown-linux-gnu_10_install.sh
    )
#  - bash ci/travisci/x86_64-unknown-linux-gnu_10_install.sh
#  - source ~/.cargo/env || true


script:
  - echo Stage script
  - echo Target=$TARGET
  - bash ci/travisci/x86_64-unknown-linux-gnu_20_script.sh

after_script: 
  - echo Stage after_script
  - set +e

before_cache:
  - echo Stage before_cache
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

cache: 
  - echo Stage cache
  - cargo

branches:
  only:
    - master

notifications:
  email:
    on_success: never
