# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

matrix:
  include:
    - os: linux 
      env: TARGET=x86_64-unknown-linux-gnu
      
    - os: osx
      env: TARGET=x86_64-apple-darwin

    - os: windows
      env: TARGET=x86_64-pc-windows-gnu

before_install:
  - echo "section: before_install"
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac
  - set -e
  - rustup self update

install:
  - echo "section: install"
  # Steps copied from the rust-sdl2 project:
  - set -xueo pipefail
  - wget https://www.libsdl.org/release/SDL2-2.0.10.tar.gz -O sdl2.tar.gz
  - tar xzf sdl2.tar.gz
  - pushd SDL2-* && ./configure && make && sudo make install && popd

  - wget -q https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
  - tar xzf SDL2_ttf-*.tar.gz
  - pushd SDL2_ttf-* && ./configure && make && sudo make install && popd

  - wget -q https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
  - tar xzf SDL2_image-*.tar.gz
  - pushd SDL2_image-* && ./configure && make && sudo make install && popd

  - wget -q https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz
  - tar xzf SDL2_mixer-*.tar.gz
  - pushd SDL2_mixer-* && ./configure && make && sudo make install && popd

  - wget -q -O SDL2_gfx-1.0.1.tar.gz https://sourceforge.net/projects/sdl2gfx/files/SDL2_gfx-1.0.1.tar.gz/download
  - tar xzf SDL2_gfx-*.tar.gz
  - pushd SDL2_gfx-* && ./autogen.sh && ./configure && make && sudo make install && popd

script:
  - echo "section: script"
  - cargo build --verbose;

before_cache:
  - echo "section: before_cache"
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    cargo
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64  

notifications:
  email: false
