name: shardoverse

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sdl2
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-image-dev
    - name: Run tests
      run: |
        cargo test --all-features --verbose