name: shardoverse

on:
  push:
  pull_request:
    branches:
      - master

jobs:

  test_Ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install SDL2-libs
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-gfx-dev 
    - uses: actions-rs/cargo@v1
      with:
        command: build

    - uses: actions-rs/cargo@v1
      with:
        command: test
      
  test_MacOS:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: | 
        brew install rustup
        rustup-init -y --default-toolchain stable        
        wget https://www.libsdl.org/release/SDL2-2.0.12.tar.gz -O sdl2.tar.gz
        tar xzf sdl2.tar.gz
        pushd SDL2-* && ./configure && make && sudo make install && popd
        wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.tar.gz -O sdl2_ttf.tar.gz
        tar xzf sdl2_ttf.tar.gz
        pushd SDL2_ttf-* && ./configure && make && sudo make install && popd
        wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz -O SDL2_image.tar.gz
        tar xzf SDL2_image.tar.gz
        pushd SDL2_image-* && ./configure && make && sudo make install && popd
        wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz -O sdl2_mixer.tar.gz
        tar xzf sdl2_mixer.tar.gz
        pushd SDL2_mixer-* && ./configure && make && sudo make install && popd
        wget --content-disposition -c https://sourceforge.net/projects/sdl2gfx/files/SDL2_gfx-1.0.4.tar.gz -O sdl2_gfx.tar.gz 
        tar xzf sdl2_gfx.tar.gz
        pushd SDL2_gfx-*/ && ./configure && make && sudo make install && popd
    - name: Build
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        export LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
        cargo build
    - name: Test
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo test
      
  test_Windows:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: | 

        # Print Powershell version.
        - ps: $PSVersionTable.PSVersion
        - ps: pwd
      
        # Install Rust and Cargo
        - curl --fail --silent --show-error --location --output rustup-init.exe https://win.rustup.rs
        - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
        - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
        - rustc -Vv
        - cargo -V
      
        # Add GCC to PATH if needed.
        - if "%TARGET%" == "i686-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw32\bin
        - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw64\bin
      
        # Install SDL2.
        - curl --fail --silent --show-error --location --output sdl2.zip https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip
        - ps: Expand-Archive sdl2.zip -DestinationPath sdl2
        - set LIB=%LIB%;C:\projects\rust-belt\sdl2\SDL2-2.0.10\lib\x64
      
        # Install SDL2_Mixer.
        - curl --fail --silent --show-error --location --output sdl2_mixer.zip https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip
        - ps: Expand-Archive sdl2_mixer.zip -DestinationPath sdl2_mixer
        - set LIB=%LIB%;C:\projects\rust-belt\sdl2_mixer\SDL2_mixer-2.0.4\lib\x64
        - ps: Get-ChildItem -Recurse -Depth 4
    
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test