name: shardoverse

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install SDL2-libs
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2 libsdl2-image libsdl2-ttf libsdl2-mixer libsdl2-gfx 

    - name: Run tests
      run: |
        cargo test --all-features --verbose