on: [push]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
        
#    - uses: actions/checkout@v1
#    - name: install_dependencies
#      run: | 
#        echo ${env:PATH}
#        
#        # Print Powershell version.
#        $PSVersionTable.PSVersion
#        pwd
#      
#        # Install Rust and Cargo
#        curl --fail --silent --show-error --location --output rustup-init.exe https://win.rustup.rs
#        rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
#        set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
#        rustc -Vv
#        cargo -V
#      
#        # Add GCC to PATH if needed.
#        #if "%TARGET%" == "i686-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw32\bin
#        #if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw64\bin
#      
#        # Install SDL2.
#        curl --fail --silent --show-error --location --output sdl2.zip https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip
#        Expand-Archive sdl2.zip -DestinationPath sdl2
#        set LIB=%LIB%;C:\projects\rust-belt\sdl2\SDL2-2.0.10\lib\x64
#      
#        # Install SDL2_Mixer.
#        curl --fail --silent --show-error --location --output sdl2_mixer.zip https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip
#        Expand-Archive sdl2_mixer.zip -DestinationPath sdl2_mixer
#        set LIB=%LIB%;C:\projects\rust-belt\sdl2_mixer\SDL2_mixer-2.0.4\lib\x64
#        Get-ChildItem -Recurse -Depth 4
#    
#    - name: Build
#      run: cargo build
#    - name: Test
#      run: cargo test