name: shardoverse

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install SDL2-libs
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-gfx-dev 

    - name: Run tests
      run: |
        cargo test --all-features --verbose

