name: shardoverse

on:
  push:
  pull_request:
    branches:
      - master

jobs:

  test_Ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: build

    - uses: actions-rs/cargo@v1
      with:
        command: test
      
  test_MacOS:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: | 
        brew install rustup
        rustup-init -y --default-toolchain stable        
    - name: Build
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        export LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
        cargo build
    - name: Test
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo test
