name: shardoverse

on:
  push:
  pull_request:
    branches:
      - master

 test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master

      - uses: actions-rs/cargo@v1
        with:
          command: build
    - name: Install SDL2-libs
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-gfx-dev 

    - name: Run tests
      run: |
        cargo test --all-features --verbose

